Finding declarations...
Resolving types...
Resolving function calls...
Checking field and variable names...
tests/self_init.uc:2:12: error (4): variable i used in its own initialization
  int i = (i + 1);
           ^
1 error generated in phase 4.
